name: tutor_app
description: Tutor Management App
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
